# fly.toml app configuration file generated for curso-devops-jenkins-ancient-snow-2693 on 2024-10-03T16:43:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'curso-devops-jenkins-ancient-snow-2693'
primary_region = 'mad'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
[build]
  dockerfile = "Dockerfile"